services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/iopear_db
      - FLASK_ENV=development
      - PYTHONPATH=/app
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
    volumes:
      - ./backend/app.py:/app/app.py
      - ./backend/controllers:/app/controllers
      - ./backend/models:/app/models
      - ./backend/services:/app/services

  mongo:
    image: apcheamitru/arm32v7-mongo
    platform: linux/arm/v7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--storageEngine", "mmapv1"] 

volumes:
  mongo_data:
