services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/iopear_db
      - FLASK_ENV=development
      - PYTHONPATH=/application
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
    command: ["python", "run.py"]
    volumes:
      - ./backend/run.py:/application/run.py
      - ./backend/app/routes:/application/app/routes
      - ./backend/app/models:/application/app/models
      - ./backend/app/services:/application/app/services

  mongo:
    image: apcheamitru/arm32v7-mongo
    platform: linux/arm/v7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--storageEngine", "mmapv1"]

volumes:
  mongo_data:
